### ISSUE TITLE
I have successfully installed according to your steps, but the picture is not displayed. What is the reason? The API key is also configured normally.

### ISSUE THREAD

**Issue by mucstudio** [ZenasMukadom/ZenSnap#1]
I have successfully installed according to your steps, but the picture is not displayed. What is the reason? The API key is also configured normally.

**Comment by ZenasMukadom** [comment]
I hope you have installed the dependencies using "npm install" and have created a .env file in the root folder of the project inside which you have inserted your API keys such as 
REACT_APP_UNSPLASH_API_KEY='XX'
REACT_APP_PIXABAY_API_KEY='XX'
REACT_APP_PEXELS_API_KEY='XX'

Where XX = Your API KEY


If you are getting the below error in the console of the browser, then your API keys are incorrect and hence no pictures will be displayed.

Failed to load resource: the server responded with a status of 401 ()
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:69)
createError @ createError.js:16
settle @ settle.js:17
handleLoad @ xhr.js:69
api.unsplash.com/search/photos?per_page=10&query=cars:1 Failed to load resource: the server responded with a status of 401 ()
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:69)
api.unsplash.com/search/photos?per_page=10&query=cars:1 Failed to load resource: the server responded with a status of 401 ()
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:69)


If you are getting some errors other than the given above, then plz do mention in your issue.
